### ISSUE TITLE
Questions about testing the model

### ISSUE THREAD

**Issue by KanaSukita** [PengyiZhang/SlimYOLOv3#3]
Thank you for your great work!
I have some questions when testing the model. I am using detect.py from [yolov3](https://github.com/ultralytics/yolov3)  for testing, the command I use is:

python3 yolov3/detect.py --cfg cfg/3iter-pruned/prune_0.5_0.5_0.7.cfg --weights weights/prune_0.5_0.5_0.7_final.weights

But I got wired results as below
![bus](https://user-images.githubusercontent.com/32619535/62002797-61e50b00-b13e-11e9-8d29-a84ebd762893.jpg)

![zidane](https://user-images.githubusercontent.com/32619535/62002799-69a4af80-b13e-11e9-827a-d8eb9295856e.jpg)

I am not sure if it's related to the configuration or something. Would you mind to provide a testing script?

**Comment by YunxinZhong** [comment]
Maybe you can try test darknet first (Use darknet)

**Comment by PengyiZhang** [comment]
@KanaSukita These models  trained specifically on aerial images might not be generalized to natural images (e.g., COCO).  Please try [images/test.jpg](https://github.com/PengyiZhang/SlimYOLOv3/blob/master/images/test.jpg)!

**Comment by KanaSukita** [comment]
@PengyiZhang Thanks, the result in [images/test.jpg](https://github.com/PengyiZhang/SlimYOLOv3/blob/master/images/test.jpg) seems much more reasonable
