### ISSUE TITLE
大神，请问不经过sparsity训练可以直接prune吗？

### ISSUE THREAD

**Issue by fengsong77** [PengyiZhang/SlimYOLOv3#36]
启动时报错
layer: 0
Traceback (most recent call last):
  File "prune.py", line 389, in <module>
    opt.perlayer_ratio,
  File "prune.py", line 160, in test
    m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'

**Comment by fengsong77** [comment]
已解决，见问题 #37

**Comment by yyx1107** [comment]
不可以啊


 
---原始邮件---
发件人: "紫晨"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 晚上6:28
收件人: "PengyiZhang/SlimYOLOv3"<SlimYOLOv3@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [PengyiZhang/SlimYOLOv3] 大神，请问不经过sparsity训练可以直接prune吗？ (#36)



已解决，见问题 #37

**Comment by yyx1107** [comment]
这个方法就是稀疏剪枝，不过也有别的不用稀疏的方法


 
---原始邮件---
发件人: "紫晨"<notifications@github.com&gt;
发送时间: 2019年9月6日(星期五) 晚上6:28
收件人: "PengyiZhang/SlimYOLOv3"<SlimYOLOv3@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [PengyiZhang/SlimYOLOv3] 大神，请问不经过sparsity训练可以直接prune吗？ (#36)



已解决，见问题 #37
