### ISSUE TITLE
That's Great, but...

### ISSUE THREAD

**Issue by DanielChowHL** [PengyiZhang/SlimYOLOv3#4]
As the reason what we already know...
How about uploading weights to Baidu net disk?

tTank you for you great work.

**Comment by PengyiZhang** [comment]
@DanielChowHL Hi, we have uploaded these pre-trained models to Baidu disk. Please feel free to download and test.

**Comment by Shivankit99** [comment]
Hi @PengyiZhang @Yoopex, could you please give the pretrained weights file. Unable to find in Baidu
