### ISSUE TITLE
prune.py error!AttributeError: 'Sequential' object has no attribute 'batch_norm_0'

### ISSUE THREAD

**Issue by zihaozhang9** [PengyiZhang/SlimYOLOv3#48]
Thank you for sharing! Great work!
I tried to run prune.py and something went wrong
I run the following code:
`Python prune.py --cfg cfg/00-unpruned/yolov3-spp3.cfg --weights yolov3-spp3_final.weights --overall_ratio 0.5 --perlayer_ratio 0.1`
Received the following error:
`File "prune.py", line 390, in <module>
     Opt.perlayer_ratio,
   File "prune.py", line 160, in test
     m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer
   File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
     Type(self).__name__, name))
AttributeError: 'Sequential' object has no attribute 'batch_norm_0'`

How should prune.py be used correctly? The weights should be saved in what way.

**Comment by A1exy** [comment]
哥们  可以把数据集发给我一份吗~   @zihaozhang9

**Comment by zihaozhang9** [comment]
> 哥们 可以把数据集发给我一份吗~ @zihaozhang9

The --data-cfg parameter is not used. Because no processing of --data-cfg was found in the prune.py code, no dataloader function was found.

**Comment by A1exy** [comment]
Thanks bro. Is that means this repo cannot be completed the pruning experiment?
I just want try it on darknet framework. You can refer https://github.com/Lam1360/YOLOv3-model-pruning(Pytorch code and I have finished pruning experiment).Their mothod both refer to "Learning Efficient Convolutional Networks Through Network Slimming". @zihaozhang9

**Comment by zihaozhang9** [comment]
Has been resolved. According to the method in question [29](https://github.com/PengyiZhang/SlimYOLOv3/issues/29#issuecomment-521903946), the prune.py code has been run successfully.
Use  ktian08-hyp branch of ultralytics, not master.Then modify the [image path](https://github.com/PengyiZhang/SlimYOLOv3/blob/master/prune.py#L323).
The command I am using is as follows:
`python prune.py --cfg cfg/00-unpruned/yolov3-spp3.cfg  --weights weights_slim/yolov3-spp3_final.weights --overall_ratio 0.5 --perlayer_ratio 0.1`

yolov3-spp3_final.weights 244M
prune_0.5_0.1/prune.weights 131M

**Comment by 1992039674** [comment]
> Has been resolved. According to the method in question [29](https://github.com/PengyiZhang/SlimYOLOv3/issues/29#issuecomment-521903946), the prune.py code has been run successfully.
> Use ktian08-hyp branch of ultralytics, not master.Then modify the [image path](https://github.com/PengyiZhang/SlimYOLOv3/blob/master/prune.py#L323).
> The command I am using is as follows:
> `python prune.py --cfg cfg/00-unpruned/yolov3-spp3.cfg --weights weights_slim/yolov3-spp3_final.weights --overall_ratio 0.5 --perlayer_ratio 0.1`
> 
> yolov3-spp3_final.weights 244M
> prune_0.5_0.1/prune.weights 131M

我的qq:1992039674,希望能交流一下，这个地方我一直报错

**Comment by 1992039674** [comment]
> Thank you for sharing! Great work!
> I tried to run prune.py and something went wrong
> I run the following code:
> `Python prune.py --cfg cfg/00-unpruned/yolov3-spp3.cfg --weights yolov3-spp3_final.weights --overall_ratio 0.5 --perlayer_ratio 0.1`
> Received the following error:
> `File "prune.py", line 390, in <module>      Opt.perlayer_ratio,    File "prune.py", line 160, in test      m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer    File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__      Type(self).__name__, name)) AttributeError: 'Sequential' object has no attribute 'batch_norm_0'`
> 
> How should prune.py be used correctly? The weights should be saved in what way.

run after "cd yolov3" , "git checkout ktian ",then appear an error  "pathspec 'ktian' did not match any file(s) known to git." ,how can I solve?please help me,thank you!!!

**Comment by 1992039674** [comment]
> > Thank you for sharing! Great work!
> > I tried to run prune.py and something went wrong
> > I run the following code:
> > `Python prune.py --cfg cfg/00-unpruned/yolov3-spp3.cfg --weights yolov3-spp3_final.weights --overall_ratio 0.5 --perlayer_ratio 0.1`
> > Received the following error:
> > `File "prune.py", line 390, in <module>      Opt.perlayer_ratio,    File "prune.py", line 160, in test      m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer    File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__      Type(self).__name__, name)) AttributeError: 'Sequential' object has no attribute 'batch_norm_0'`
> > How should prune.py be used correctly? The weights should be saved in what way.
> 
> run after "cd yolov3" , "git checkout ktian ",then appear an error "pathspec 'ktian' did not match any file(s) known to git." ,how can I solve?please help me,thank you!!!

I have solve it by this code: https://github.com/fengsong77/yolov3

**Comment by Arc2019** [comment]
@zihaozhang9 : Could you possibly share your pruned weights? I am getting the same error and when I try to use 'ktian' branch , I get another set of errors. 
"RuntimeError: Error(s) in loading state_dict for Darknet:"Missing key(s) in state_dict: "module_list.0.conv_0.weight", "module_list.0.batch_norm_0.weight", "module_list.0.batch_norm_0.bias", "module_list.0.batch_norm_0.running_mean", "module_list.0.batch_norm_0.running_var", "module_list.1.conv_1.weight", "module_list.1.batch_norm_1.weight", "module_list.1.batch_norm_1.bias", "module_list.1.batch_norm_1.running_mean", "module_list.1.batch_norm_1.running_var", "module_list.2.conv_2.weight", "module_list.2.batch_norm_2.weight", "module_list.2.batch_norm_2.bias", "module_list.2.batch_norm_2.running_mean", "module_list.2.batch_norm_2.running_var", "module_list.3.conv_3.weight", "module_list.3.batch_norm_3.weight", "module_list.3.batch_norm_3.bias", "module_list.3.batch_norm_3.running_mean", "module_list.3.batch_norm_3.running_var", "module_list.5.conv_5.weight", "module_list.5.batch_norm_5.weight", "module_list.5.batch_norm_5.bias", "module_list.5.batch_norm_5.running_mean", "module_list.5.batch_norm_5.running_var", "module_list.6.conv_6.weight", "module_list.6.batch_norm_6.weight", "module_list.6.batch_norm_6.bias", "module_list.6.batch_norm_6.running_mean", "module_list.6.batch_norm_6.running_var", "module_list.7.conv_7.weight",..........................................................................

**Comment by zihaozhang9** [comment]
> @zihaozhang9 : Could you possibly share your pruned weights? I am getting the same error and when I try to use 'ktian' branch , I get another set of errors.
> "RuntimeError: Error(s) in loading state_dict for Darknet:"Missing key(s) in state_dict: "module_list.0.conv_0.weight", "module_list.0.batch_norm_0.weight", "module_list.0.batch_norm_0.bias", "module_list.0.batch_norm_0.running_mean", "module_list.0.batch_norm_0.running_var", "module_list.1.conv_1.weight", "module_list.1.batch_norm_1.weight", "module_list.1.batch_norm_1.bias", "module_list.1.batch_norm_1.running_mean", "module_list.1.batch_norm_1.running_var", "module_list.2.conv_2.weight", "module_list.2.batch_norm_2.weight", "module_list.2.batch_norm_2.bias", "module_list.2.batch_norm_2.running_mean", "module_list.2.batch_norm_2.running_var", "module_list.3.conv_3.weight", "module_list.3.batch_norm_3.weight", "module_list.3.batch_norm_3.bias", "module_list.3.batch_norm_3.running_mean", "module_list.3.batch_norm_3.running_var", "module_list.5.conv_5.weight", "module_list.5.batch_norm_5.weight", "module_list.5.batch_norm_5.bias", "module_list.5.batch_norm_5.running_mean", "module_list.5.batch_norm_5.running_var", "module_list.6.conv_6.weight", "module_list.6.batch_norm_6.weight", "module_list.6.batch_norm_6.bias", "module_list.6.batch_norm_6.running_mean", "module_list.6.batch_norm_6.running_var", "module_list.7.conv_7.weight",..........................................................................

I have given the [solution ](https://github.com/PengyiZhang/SlimYOLOv3/issues/48#issuecomment-542201123)above. This is usually caused by a mismatch in the names of the layers.
I haven't read this project library for a long time and have forgotten it. Recently I was reading another [project library](https://github.com/tanluren/yolov3-channel-and-layer-pruning) which contains more pruning schemes you can read.

**Comment by MuhammadAsadJaved** [comment]
> > Thank you for sharing! Great work!
> > I tried to run prune.py and something went wrong
> > I run the following code:
> > `Python prune.py --cfg cfg/00-unpruned/yolov3-spp3.cfg --weights yolov3-spp3_final.weights --overall_ratio 0.5 --perlayer_ratio 0.1`
> > Received the following error:
> > `File "prune.py", line 390, in <module>      Opt.perlayer_ratio,    File "prune.py", line 160, in test      m = getattr(module, 'batch_norm_%d' % i) # batch_norm layer    File "/home/nnir712/anaconda3/envs/zzhpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__      Type(self).__name__, name)) AttributeError: 'Sequential' object has no attribute 'batch_norm_0'`
> > How should prune.py be used correctly? The weights should be saved in what way.
> 
> run after "cd yolov3" , "git checkout ktian ",then appear an error "pathspec 'ktian' did not match any file(s) known to git." ,how can I solve?please help me,thank you!!!

try this method 

git clone https://github.com/ultralytics/yolov3

cd yolov3

git checkout ktian08-hyp & git pull

**Comment by Wellington-Noberto** [comment]
I'm trying to clone this other brach, but it seems that the only branch available is the master
![image](https://user-images.githubusercontent.com/46430006/87975775-771b1e00-caa2-11ea-98c2-7b01929c782d.png)
![image](https://user-images.githubusercontent.com/46430006/87975927-a6ca2600-caa2-11ea-9720-cdd93148f6eb.png)

**Comment by MuhammadAsadJaved** [comment]
> I'm trying to clone this other brach, but it seems that the only branch available is the master
> ![image](https://user-images.githubusercontent.com/46430006/87975775-771b1e00-caa2-11ea-98c2-7b01929c782d.png)
> ![image](https://user-images.githubusercontent.com/46430006/87975927-a6ca2600-caa2-11ea-9720-cdd93148f6eb.png)

Please try the same commands as it is. it's available.  Thank you

**Comment by leodsti** [comment]
> > I'm trying to clone this other brach, but it seems that the only branch available is the master
> > ![image](https://user-images.githubusercontent.com/46430006/87975775-771b1e00-caa2-11ea-98c2-7b01929c782d.png)
> > ![image](https://user-images.githubusercontent.com/46430006/87975927-a6ca2600-caa2-11ea-9720-cdd93148f6eb.png)
> 
> Please try the same commands as it is. it's available. Thank you

I am having the same issue, it says that the "error: pathspec 'ktian08-hyp' did not match any file(s) known to git."

have you found a solution ?

Thanks

**Comment by Wellington-Noberto** [comment]
> > > I'm trying to clone this other brach, but it seems that the only branch available is the master
> > > ![image](https://user-images.githubusercontent.com/46430006/87975775-771b1e00-caa2-11ea-98c2-7b01929c782d.png)
> > > ![image](https://user-images.githubusercontent.com/46430006/87975927-a6ca2600-caa2-11ea-9720-cdd93148f6eb.png)
> > 
> > 
> > Please try the same commands as it is. it's available. Thank you
> 
> I am having the same issue, it says that the "error: pathspec 'ktian08-hyp' did not match any file(s) known to git."
> 
> have you found a solution ?
> 
> Thanks

Use this instead:
https://github.com/tanluren/yolov3-channel-and-layer-pruning

**Comment by leodsti** [comment]
> > > > I'm trying to clone this other brach, but it seems that the only branch available is the master
> > > > ![image](https://user-images.githubusercontent.com/46430006/87975775-771b1e00-caa2-11ea-98c2-7b01929c782d.png)
> > > > ![image](https://user-images.githubusercontent.com/46430006/87975927-a6ca2600-caa2-11ea-9720-cdd93148f6eb.png)
> > > 
> > > 
> > > Please try the same commands as it is. it's available. Thank you
> > 
> > 
> > I am having the same issue, it says that the "error: pathspec 'ktian08-hyp' did not match any file(s) known to git."
> > have you found a solution ?
> > Thanks
> 
> Use this instead:
> https://github.com/tanluren/yolov3-channel-and-layer-pruning

Do you mean that this repo is no longer supported?
In addition to the Pruning I was looking a lot at the conversion between Darknet & Pytorch, which is not available in https://github.com/tanluren/yolov3-channel-and-layer-pruning if I am not mistaken.

**Comment by Wellington-Noberto** [comment]
This new repo that I showed you is based on ultralytics/yolov3, so it supports conversion between darknet & pytorch. Actually, you don't even need to convert your .weights to .pt file, the training function in this repo accepts your .weights file.
The suggestion I give to you is that you use darknet to make the normal training and fine-tuning, and use this repo to make the sparse training and layer pruning

**Comment by Wellington-Noberto** [comment]
> > > > > I'm trying to clone this other brach, but it seems that the only branch available is the master
> > > > > ![image](https://user-images.githubusercontent.com/46430006/87975775-771b1e00-caa2-11ea-98c2-7b01929c782d.png)
> > > > > ![image](https://user-images.githubusercontent.com/46430006/87975927-a6ca2600-caa2-11ea-9720-cdd93148f6eb.png)
> > > > 
> > > > 
> > > > Please try the same commands as it is. it's available. Thank you
> > > 
> > > 
> > > I am having the same issue, it says that the "error: pathspec 'ktian08-hyp' did not match any file(s) known to git."
> > > have you found a solution ?
> > > Thanks
> > 
> > 
> > Use this instead:
> > https://github.com/tanluren/yolov3-channel-and-layer-pruning
> 
> Do you mean that this repo is no longer supported?
> In addition to the Pruning I was looking a lot at the conversion between Darknet & Pytorch, which is not available in https://github.com/tanluren/yolov3-channel-and-layer-pruning if I am not mistaken.

This repo that I showed you in based on ultralytics/yolov3, so it supports this kind of conversion. 
Actually, you don't even need to make this conversion because the training function accepts your .weights file.
But I recommend you to use the darknet repo to make the normal training in fine-tune your model, and use this repo just for sparse training and pruning layers

**Comment by leodsti** [comment]
> > > > > > I'm trying to clone this other brach, but it seems that the only branch available is the master
> > > > > > ![image](https://user-images.githubusercontent.com/46430006/87975775-771b1e00-caa2-11ea-98c2-7b01929c782d.png)
> > > > > > ![image](https://user-images.githubusercontent.com/46430006/87975927-a6ca2600-caa2-11ea-9720-cdd93148f6eb.png)
> > > > > 
> > > > > 
> > > > > Please try the same commands as it is. it's available. Thank you
> > > > 
> > > > 
> > > > I am having the same issue, it says that the "error: pathspec 'ktian08-hyp' did not match any file(s) known to git."
> > > > have you found a solution ?
> > > > Thanks
> > > 
> > > 
> > > Use this instead:
> > > https://github.com/tanluren/yolov3-channel-and-layer-pruning
> > 
> > 
> > Do you mean that this repo is no longer supported?
> > In addition to the Pruning I was looking a lot at the conversion between Darknet & Pytorch, which is not available in https://github.com/tanluren/yolov3-channel-and-layer-pruning if I am not mistaken.
> 
> This repo that I showed you in based on ultralytics/yolov3, so it supports this kind of conversion.
> Actually, you don't even need to make this conversion because the training function accepts your .weights file.
> But I recommend you to use the darknet repo to make the normal training in fine-tune your model, and use this repo just for sparse training and pruning layers

Thanks, I will check it out and let you know ;)
